export enum ELEMENTS {
  CONSTRUCTORS = 'constructors',
  GETTERS = 'getters',
  OTHER = 'other',
  PRIVATE_METHODS = 'private-methods',
  PRIVATE_PROPERTIES = 'private-properties',
  PRIVATE_STATIC_METHODS = 'private-static-methods',
  PRIVATE_STATIC_PROPERTIES = 'private-static-properties',
  PUBLIC_METHODS = 'public-methods',
  PUBLIC_PROPERTIES = 'public-properties',
  PUBLIC_STATIC_METHODS = 'public-static-methods',
  PUBLIC_STATIC_PROPERTIES = 'public-static-properties',
  SETTERS = 'setters',
  STATIC_METHODS = 'static-methods',
  STATIC_PROPERTIES = 'static-properties',
}
